# Generated by Django 3.0.4 on 2020-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('Espera', 'Espera'), ('Realizada', 'Realizada')], default='Agendada', max_length=9, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Cirurgia', 'Cirurgia'), ('Clínica Geral', 'Clínica Geral'), ('Gastroenterologia', 'Gastroenterologia'), ('Neurologia', 'Neurologia'), ('Odontologia', 'Odontologia'), ('Oftalmologia', 'Oftalmologia'), ('Ortopedia', 'Ortopedia'), ('Pediatria', 'Pediatria')], max_length=50, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(choices=[('08h-09h', '08h-09h'), ('09h-10h', '09h-10h'), ('10h-11h', '10h-11h')], max_length=7, verbose_name='Horario'),
        ),
    ]
