# Generated by Django 3.0.4 on 2020-04-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_consulta_set', to='core.Medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_consulta_set', to='core.Paciente', verbose_name='Paciente'),
        ),
        migrations.RemoveField(
            model_name='medico',
            name='consultas',
        ),
        migrations.AddField(
            model_name='medico',
            name='consultas',
            field=models.ManyToManyField(related_name='consultas_medico_set', to='core.Consulta'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='consultas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='consultas',
            field=models.ManyToManyField(related_name='consultas_paciente_set', to='core.Consulta'),
        ),
    ]
