# Generated by Django 3.0.4 on 2020-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='especialidade',
            field=models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Cirurgia', 'Cirurgia'), ('Clínica Geral', 'Clínica Geral'), ('Gastroenterologia', 'Gastroenterologia'), ('Neurologia', 'Neurologia'), ('Odontologia', 'Odontologia'), ('Oftalmologia', 'Oftalmologia'), ('Ortopedia', 'Ortopedia'), ('Pediatria', 'Pediatria')], max_length=50, verbose_name='Especialidade'),
        ),
    ]
