# Generated by Django 3.0.4 on 2020-03-28 21:30

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
                ('objects', core.models.PacienteManager()),
            ],
        ),
    ]
