# Generated by Django 3.0.4 on 2020-04-06 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200405_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='modificado',
        ),
    ]
