# Generated by Django 3.0.4 on 2020-03-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200321_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidade',
            old_name='especialidade',
            new_name='nome',
        ),
    ]
