# Generated by Django 3.0.4 on 2020-04-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200406_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='lista_espera',
        ),
    ]
