# Generated by Django 3.0.4 on 2020-03-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especialidade', verbose_name='Especialidade'),
        ),
    ]
