# Generated by Django 3.0.4 on 2020-04-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consulta_lista_espera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fila',
            old_name='consultas',
            new_name='consulta_origem',
        ),
    ]
