# Generated by Django 3.0.4 on 2020-04-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200412_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fila',
        ),
    ]
