# Generated by Django 3.0.4 on 2020-04-26 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacao_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Paciente', verbose_name='Paciente'),
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
