# Generated by Django 3.0.4 on 2020-04-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200426_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('mensagem', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mensagem')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_notificacao_set', to='core.Paciente', verbose_name='Notificação')),
            ],
        ),
    ]
