# Generated by Django 3.0.4 on 2020-04-27 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notificacao_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_notificacao_set', to='core.Paciente', verbose_name='Consulta'),
        ),
    ]
