# Generated by Django 3.0.4 on 2020-04-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificacao_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_notificacao_set', to='core.Consulta', verbose_name='Consulta'),
        ),
    ]
