# Generated by Django 3.0.4 on 2020-05-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200427_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
