# Generated by Django 3.0.4 on 2020-05-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200510_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='suport',
            new_name='suporte',
        ),
    ]
