# Generated by Django 3.0.4 on 2020-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200512_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('Espera', 'Espera'), ('Realizada', 'Realizada'), ('Expirada', 'Expirada')], default='Agendada', max_length=9, verbose_name='Estado'),
        ),
    ]
