# Generated by Django 3.0.4 on 2020-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200513_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Cancelada', 'Cancelada'), ('Espera', 'Espera'), ('Realizada', 'Realizada')], default='Agendada', max_length=9, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='telefone',
            field=models.CharField(max_length=17, verbose_name='Telefone'),
        ),
    ]
